version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "egghead"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4yc0scv2wusr"
s3_prefix = "egghead"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
